# This is a basic workflow to help you get started with Actions

name: Build And Deploy

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy VLA
                uses: appleboy/ssh-action@v0.1.4
                with:
                    host: ${{ secrets.W1_HOST }}
                    port: ${{ secrets.W1_PORT }}
                    username: ${{ secrets.W1_USERNAME }}
                    password: ${{ secrets.W1_PASSWORD }}

                    script: |
                        cd ~/public_html/
                        git pull
                        cp .env .env.backup
                        cp .env .env.local
                        cp .env .env.test
                        composer install
                        bin/console cache:clear
                        echo "Deployment successful!"
